# -*- coding: utf-8 -*-
"""Simulador de Epidemias: Probabilidade de Infecção

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fZ5nZGVv0Yaf2ehxnRzO1xnWwgXRO28
"""

import numpy as np
import matplotlib.pyplot as plt

def simular_propagacao(populacao_total, infectados_iniciais, dias, prob_infeccao, num_simulacoes):
    resultados = []

    for _ in range(num_simulacoes):
        infectados = infectados_iniciais
        historico_infectados = [infectados]

        for _ in range(dias):
            novos_infectados = 0
            for _ in range(infectados):
                if np.random.rand() < prob_infeccao:
                    novos_infectados += 1

            infectados = min(populacao_total, infectados + novos_infectados)
            historico_infectados.append(infectados)

        resultados.append(historico_infectados)

    return np.array(resultados)

populacao_total = 1000
infectados_iniciais = 1
dias = 30
prob_infeccao = 0.20
num_simulacoes = 1000


resultados = simular_propagacao(populacao_total, infectados_iniciais, dias, prob_infeccao, num_simulacoes)

mais_de_50_porcento = np.mean(resultados[:, -1] > (populacao_total * 0.5))
print(f'Probabilidade de mais de 50% da população ser infectada: {mais_de_50_porcento * 100:.2f}%')

plt.figure(figsize=(10, 6))
for i in range(10):
    plt.plot(resultados[i], label=f'Simulação {i+1}')
plt.title('Simulação da Propagação de uma Doença Infecciosa em 1000 Pessoas')
plt.xlabel('Dias')
plt.ylabel('Número de Infectados')
plt.grid(True)
plt.savefig('simulacao_epidemiologia.png')
plt.show()